packages:
  - .

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - canvas
  - prisma

onlyBuiltDependencies:
  - bcrypt
  - unrs-resolver

overrides:
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  next-auth@>=5.0.0-beta.0 <5.0.0-beta.30: '>=5.0.0-beta.30'
  next@=14.2.25: '>=14.2.26'
  next@>=0.9.9 <14.2.31: '>=14.2.31'
  next@>=0.9.9 <14.2.32: '>=14.2.32'
  next@>=13.0 <14.2.30: '>=14.2.30'
  nodemailer@<7.0.7: '>=7.0.7'
  pdfjs-dist@<=4.1.392: '>=4.2.67'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
