// Auto-generated by scripts/export-seed.ts
// This file captures the current database state for reseeding.
// Do not edit manually. Regenerate via: bun run seed:dump

import { PrismaClient } from "@prisma/client";

const seedData = {
  "users": [
    {
      "id": "288b04ec-bdf5-4134-a529-d725cca29665",
      "name": "Bhavesh Patil",
      "email": "bhaveshpatil918@gmail.com",
      "emailVerified": null,
      "username": "Uraniumking007",
      "image": null,
      "password": "github-auth",
      "isAdmin": true,
      "isDemo": false
    }
  ],
  "accounts": [],
  "sessions": [],
  "verificationTokens": [],
  "technologies": [],
  "categories": [],
  "projects": [
    {
      "id": "09a1ba73-5653-4590-b2cd-abbf1f947c2a",
      "name": "Expense Manager",
      "description": "This is a simple web-based expense manager application that allows you to add, edit, and delete your expenses. The data is stored persistently on the client-side using the browser's local storage.",
      "image": "https://r2.fivemanage.com/image/VCw3xbPYVUBm.png",
      "link": "https://expensemanager.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/Expense-Manager",
      "tech": [
        "Basic HTML",
        "Javascript",
        "CSS"
      ],
      "createdAt": "2025-05-07T11:41:15.555Z",
      "updatedAt": "2025-11-01T09:39:21.691Z",
      "projectInitiated": "2023-01-14T00:00:00.000Z",
      "projectCompleted": "2023-03-15T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/gx4ffo.png"
      ]
    },
    {
      "id": "1dbe1439-c29f-4746-87d9-0195500ad2d5",
      "name": "Previous Portfolio",
      "description": "What is there to say, I mean?",
      "image": "https://r2.fivemanage.com/image/nBQQKMUni21j.png",
      "link": "https://obsolete.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/Website-Main",
      "tech": [
        "HTML",
        "Javascript",
        "Css"
      ],
      "createdAt": "2025-05-07T11:59:01.097Z",
      "updatedAt": "2025-11-01T09:40:47.207Z",
      "projectInitiated": "2023-01-01T00:00:00.000Z",
      "projectCompleted": "2023-02-01T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/wjD1Ca.png"
      ]
    },
    {
      "id": "2838451b-cdfd-430e-b4f4-0fffc0378342",
      "name": "Image Hosting Site (Internship, Localhost)",
      "description": "It is an image hosting site where you can host as many images as your browser's application local storage supports. I made it on the first day of my first-ever internship.",
      "image": "https://r2.fivemanage.com/image/LQqVf7xdDDbM.png",
      "link": "https://local-image.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/LocalStorage-Image-Gallery",
      "tech": [
        "javascript",
        "html",
        "css"
      ],
      "createdAt": "2025-05-07T11:25:02.068Z",
      "updatedAt": "2025-11-01T09:42:11.669Z",
      "projectInitiated": "2023-07-29T00:00:00.000Z",
      "projectCompleted": "2023-08-21T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/quqLXl.png"
      ]
    },
    {
      "id": "34469d55-da85-46dc-ad68-a51b46d19797",
      "name": "Stopwatch",
      "description": "This is a simple stopwatch app built with JavaScript. Read about how to build it on my blog.",
      "image": "https://r2.fivemanage.com/image/GlJfCaORRZSd.jpg",
      "link": "https://stopwatch.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/stopwatch",
      "tech": [
        "Basic Html",
        "Javascript",
        "css"
      ],
      "createdAt": "2025-05-07T11:37:01.023Z",
      "updatedAt": "2025-11-01T09:40:09.038Z",
      "projectInitiated": "2022-12-21T00:00:00.000Z",
      "projectCompleted": "2023-01-10T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/Cd7nDa.jpg"
      ]
    },
    {
      "id": "71ccab40-cf26-4c0b-8a50-a5d5eb8504e6",
      "name": "Tasky",
      "description": "This is a task management app.",
      "image": "https://r2.fivemanage.com/image/RhpP3ohbxUyk.png",
      "link": "https://tasky.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/Tasky",
      "tech": [
        "react",
        "Next.js",
        "tailwind",
        "prisma",
        "supabase",
        "postgres"
      ],
      "createdAt": "2025-05-07T11:53:00.410Z",
      "updatedAt": "2025-11-01T09:40:19.647Z",
      "projectInitiated": "2023-08-15T00:00:00.000Z",
      "projectCompleted": null,
      "isCompleted": false,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/IV4T7m.png"
      ]
    },
    {
      "id": "8df79f81-dcb0-4fcb-af1c-3138277537ce",
      "name": "Once Human Assistant",
      "description": "OH Assistant serves as a comprehensive resource for Once Human, providing guides, tools, and community support. Whether you're a beginner or an experienced player, we provide step-by-step tutorials, resource guides, and advanced strategies to enhance your gameplay.",
      "image": "https://r2.fivemanage.com/image/Gj2makGv4LuM.png",
      "link": "https://ohassistant.com/",
      "github": "https://github.com/Uraniumking007/once_human_outpost",
      "tech": [
        "Next.js",
        "Tailwind",
        "shadcn",
        "prisma",
        "xata"
      ],
      "createdAt": "2025-05-07T12:03:42.920Z",
      "updatedAt": "2025-11-14T08:55:24.379Z",
      "projectInitiated": "2025-03-15T00:00:00.000Z",
      "projectCompleted": "2025-11-12T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": true,
      "images": [
        "https://i.vgy.me/dIg8x0.png"
      ]
    },
    {
      "id": "b0c11ce0-e843-4f05-a3b1-fc8e887cbf19",
      "name": "SkipSquad",
      "description": "This is a user-friendly tool designed to help students manage their attendance, track their progress, and improve their educational outcomes.",
      "image": "https://r2.fivemanage.com/image/78t4HfjDvpKm.png",
      "link": "https://skipsquad.vercel.app/",
      "github": "",
      "tech": [
        "nextjs",
        "daisyui",
        "react",
        "prisma",
        "clerk"
      ],
      "createdAt": "2025-05-09T06:06:24.308Z",
      "updatedAt": "2025-11-01T09:41:22.581Z",
      "projectInitiated": "2023-03-29T00:00:00.000Z",
      "projectCompleted": "2023-05-23T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": true,
      "images": [
        "https://i.vgy.me/XHeVUe.png"
      ]
    },
    {
      "id": "b84ff581-8925-47ef-b892-c12a726c121d",
      "name": "Snippy",
      "description": "This is a code-sharing platform.",
      "image": "https://r2.fivemanage.com/image/jyF29kBGSHrg.png",
      "link": "https://snippy-bb.vercel.app/",
      "github": "https://github.com/bug-busterss/snippy",
      "tech": [
        "Next.js",
        "tailwind",
        "prisma",
        "supabase",
        "Tiptap",
        "Drizzle"
      ],
      "createdAt": "2025-05-07T11:49:39.996Z",
      "updatedAt": "2025-11-01T09:39:37.539Z",
      "projectInitiated": "2023-09-26T00:00:00.000Z",
      "projectCompleted": "2023-09-30T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": true,
      "images": [
        "https://i.vgy.me/3JPrFq.png"
      ]
    },
    {
      "id": "ba1bbcd0-42ca-48e3-850c-2108d5b2759a",
      "name": "Todo App",
      "description": "This is a simple web application for managing your todo list. You can add, edit, and delete tasks, and mark them as completed when you're done.",
      "image": "https://r2.fivemanage.com/image/fSeH8WVVFxIZ.png",
      "link": "https://todo.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/todo-app-new",
      "tech": [
        "Javascript",
        "CSS"
      ],
      "createdAt": "2025-05-07T11:44:25.800Z",
      "updatedAt": "2025-11-01T09:39:59.056Z",
      "projectInitiated": "2023-02-25T00:00:00.000Z",
      "projectCompleted": "2023-03-27T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/krwQqc.png"
      ]
    },
    {
      "id": "d7c3262c-320c-4b08-bf19-cb24a50558ed",
      "name": "Digital Clock",
      "description": "A simple digital clock. Used to learn Date function.",
      "image": "https://r2.fivemanage.com/image/HMbtdS4mStCM.png",
      "link": "https://digitalclock.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/digital-clock",
      "tech": [
        "Basic HTML",
        "Javascript",
        "css"
      ],
      "createdAt": "2025-05-07T11:39:25.127Z",
      "updatedAt": "2025-11-01T09:41:34.369Z",
      "projectInitiated": "2023-01-18T00:00:00.000Z",
      "projectCompleted": "2023-01-19T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/4lbJ5p.png"
      ]
    },
    {
      "id": "ddf51b0d-002d-4cdd-a17b-81fec6faeb3e",
      "name": "Ecommerce Site (Internship, Localstorage)",
      "description": "This is a simple e-Commerce website which stores data in local storage of your browser.",
      "image": "https://i.vgy.me/IYA1VU.png",
      "link": "http://ecommerce-local.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/localstorage-shop",
      "tech": [
        "React",
        "Next.js",
        "Tailwind",
        "frontend"
      ],
      "createdAt": "2025-05-07T11:33:51.389Z",
      "updatedAt": "2025-08-11T02:09:30.874Z",
      "projectInitiated": "2023-07-29T00:00:00.000Z",
      "projectCompleted": "2023-07-29T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/IYA1VU.png",
        "https://i.vgy.me/wfESaT.png",
        "https://i.vgy.me/9JwyXJ.png"
      ]
    },
    {
      "id": "e8502db7-707c-42f8-a249-ca6dfe8fa094",
      "name": "Temperature Converter (Learning JS)",
      "description": "Just converts units of temperature to other units.",
      "image": "https://r2.fivemanage.com/image/U7noGjC0vISk.png",
      "link": "https://tempconvert.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/Temperature-Converter",
      "tech": [
        "Basic Html",
        "javascript",
        "html",
        "css",
        "Frontend"
      ],
      "createdAt": "2025-05-07T10:48:43.137Z",
      "updatedAt": "2025-11-01T09:41:06.850Z",
      "projectInitiated": "2022-12-10T00:00:00.000Z",
      "projectCompleted": "2022-12-24T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/VJu3kQ.png"
      ]
    },
    {
      "id": "f6a0290d-1b7c-41b0-af50-e9b130cd807f",
      "name": "Metaverse Asia Roleplay",
      "description": "The application portal and Admin panel for the Metaverse Asia Roleplay server.",
      "image": "https://r2.fivemanage.com/image/MlO06inlJYaC.png",
      "link": "https://application.metaverseasiarp.xyz/",
      "github": "https://github.com/Uraniumking007/MetaverseAsiaApplications",
      "tech": [
        "nextjs",
        "shadcn",
        "tRPC",
        "authjs",
        "postgres"
      ],
      "createdAt": "2025-09-01T05:35:51.043Z",
      "updatedAt": "2025-09-01T05:40:20.022Z",
      "projectInitiated": "2025-07-17T00:00:00.000Z",
      "projectCompleted": "2025-08-31T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://r2.fivemanage.com/image/MlO06inlJYaC.png",
        "https://r2.fivemanage.com/image/NHz0ZMujQfxE.png",
        "https://r2.fivemanage.com/image/FEfquKeVfw2A.png",
        "https://r2.fivemanage.com/image/lzdJiVtKrvJr.png",
        "https://r2.fivemanage.com/image/LqtSULRvPiU1.png",
        "https://r2.fivemanage.com/image/mIGZ1MSTqLJa.png"
      ]
    },
    {
      "id": "10c8e93f-032d-4ecb-bf9a-9b6fa05f67f9",
      "name": "Blogify",
      "description": "This is a blogging platform with a rich text editor. Made for College Final Year Project",
      "image": "https://r2.fivemanage.com/image/E2HYOwyI1qfB.png",
      "link": "http://blogify.bhaveshp.dev/",
      "github": "https://github.com/Uraniumking007/blogify",
      "tech": [
        "Next.js",
        "tailwind",
        "daisyui",
        "clerk",
        "supabase",
        "prisma",
        "Tiptap"
      ],
      "createdAt": "2025-05-07T11:56:46.684Z",
      "updatedAt": "2025-12-10T09:54:16.719Z",
      "projectInitiated": "2023-11-01T00:00:00.000Z",
      "projectCompleted": "2024-05-03T00:00:00.000Z",
      "isCompleted": true,
      "categories": [],
      "endDate": null,
      "isFeatured": false,
      "images": [
        "https://i.vgy.me/edYXFv.png"
      ]
    }
  ],
  "projectTechnologies": [],
  "projectCategories": [],
  "certifications": [
    {
      "id": "cmadsdssm0000jyrs00s004db",
      "title": "Programming using Java",
      "issuer": "Infosys | Springboard",
      "date": "2025-03-31T00:00:00.000Z",
      "description": "The course provided me with an introduction to the fundamentals of object-oriented programming and Java as the programming language.",
      "imageUrl": "https://i.vgy.me/Y0FCKU.png",
      "credentialUrl": null,
      "createdAt": "2025-05-07T10:19:26.832Z",
      "updatedAt": "2025-05-15T10:11:35.107Z",
      "pdfUrl": "https://drive.google.com/file/d/1XiVj-__E7BNtLoVwzLjgbfIIbzvAw-6D/view",
      "visible": "public"
    },
    {
      "id": "cmadt5v8d0000fq3xj883bo7i",
      "title": "Basics of Python",
      "issuer": "Infosys | Springboard",
      "date": "2024-07-30T00:00:00.000Z",
      "description": "This course provided me with an understanding of the fundamental concepts of Python, which are the basis of this programming language.",
      "imageUrl": "https://i.vgy.me/NwpUHE.png",
      "credentialUrl": "https://verify.onwingspan.com/",
      "createdAt": "2025-05-07T10:41:16.381Z",
      "updatedAt": "2025-05-07T10:42:20.691Z",
      "pdfUrl": "https://drive.google.com/file/d/1XiVj-__E7BNtLoVwzLjgbfIIbzvAw-6D/view",
      "visible": "public"
    },
    {
      "id": "cmap8kn5c0000e2kfsgz8ow6i",
      "title": "Inspire 2k25 C-Evolution",
      "issuer": "C.K Pithawalla College of Engineering & Technology",
      "date": "2025-03-07T00:00:00.000Z",
      "description": "Participation in C Quiz",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/Acrobat_ed5rqJ2xka_Tdb06aTDk.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:38:07.724Z",
      "updatedAt": "2025-05-15T10:56:17.177Z",
      "pdfUrl": "https://drive.google.com/file/d/14VgxXaKuda-e4tVDSHzs7dCfdBYfHzqQ/view",
      "visible": "public"
    },
    {
      "id": "cmap8ozgg0001e2kfd93n03wt",
      "title": "Internship in Web development with React",
      "issuer": "Sridix Technology",
      "date": "2023-06-09T00:00:00.000Z",
      "description": "Developed three websites. Two of which utilize the browser's local storage as a database. while the final one is a fully developed project that utilizes Supabase Postgres as its database.",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/Acrobat_xqsDa3NROJ_ttQqfqe-u.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:41:30.474Z",
      "updatedAt": "2025-05-15T10:41:30.474Z",
      "pdfUrl": "https://drive.google.com/file/d/1QwSalh7e1PLsdqznDqb3-UKnAbGFve0V/view",
      "visible": "public"
    },
    {
      "id": "cmap8szae0002e2kfok2r24ru",
      "title": "Best Solution to Impact Academia",
      "issuer": "Indian Society of Technical Education, Gujarat Section (ISTE)",
      "date": "2023-03-25T00:00:00.000Z",
      "description": "We won an award for Best Solution to impact Acedemia. a state-level programming competition organized by the Indian Society for Technical Education (STE), Gujarat Section, and B&B Institute of Technology, Vallabh Vidyanagar.",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/Acrobat_uNWJadRgdI_bXXIH9MDx.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:44:36.878Z",
      "updatedAt": "2025-05-15T10:44:36.878Z",
      "pdfUrl": "https://drive.google.com/file/d/1Y0QwZmUiTi2U4bGc2m3iTefMieNzvrvI/view",
      "visible": "public"
    },
    {
      "id": "cmap8vn1o0003e2kfdj3rb7d6",
      "title": "Pythakon - 2k22",
      "issuer": "CHARUSAT campus",
      "date": "2022-08-06T00:00:00.000Z",
      "description": "Participation in the national level hackathon Pythakon-2k22\nduring 5-6 August at CHARUSAT campus, Changa, Anand, Gujarat.",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/Acrobat_C1kwGr1K4Y_-MCqKg7EZ.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:46:40.981Z",
      "updatedAt": "2025-05-15T10:46:40.981Z",
      "pdfUrl": "https://drive.google.com/file/d/1Saew0rlf1HLgH5tRf0nazEBWqVJjmhSD/view",
      "visible": "public"
    },
    {
      "id": "cmap8yrwl0004e2kfu9q2cc2p",
      "title": "SSIP Regional Round 2022",
      "issuer": "AURO University & SSIP",
      "date": "2022-10-08T00:00:00.000Z",
      "description": "Participation in the Regional Round of Azadi ka Amrit Mahotsav Hackathon-2022 during 7th & 8th October, 2022, held at AURO University, Surat.",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/chrome_gRMtSdjgEw_keQMClG2ZS.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:49:07.246Z",
      "updatedAt": "2025-05-15T10:49:07.246Z",
      "pdfUrl": "https://drive.google.com/file/d/1tE99A-mWq6z8bXK4utQdv1kDsAbLJNPe/view",
      "visible": "public"
    },
    {
      "id": "cmap91khb0005e2kfodgr7i57",
      "title": "College Level Shark Tank like Event Coordinator",
      "issuer": "C.K Pithawalla College of Engineering & Technology",
      "date": "2025-03-08T00:00:00.000Z",
      "description": "Shark Tank Event Coordinator in INSPIRE '25, a national-level technical festival held on March 7 & 8, 2025, at C. K. Pithawala Campus.",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/chrome_OMgpLhDpjM_6ffpdyIpm.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:51:17.590Z",
      "updatedAt": "2025-05-15T10:56:10.483Z",
      "pdfUrl": "https://drive.google.com/file/d/1a_4l1EZiFsVnzZ7P6Gz_By99mDX5b84W/view",
      "visible": "public"
    },
    {
      "id": "cmap9a17k0000joqwq6ydwyz3",
      "title": "Innov8 Hackathon Participation 2023",
      "issuer": "JECRC University",
      "date": "2024-02-08T00:00:00.000Z",
      "description": "",
      "imageUrl": "https://ik.imagekit.io/i6dlpbs14/certifications/chrome_U6HvhFU584_dquBz-UGu.png",
      "credentialUrl": null,
      "createdAt": "2025-05-15T10:57:52.522Z",
      "updatedAt": "2025-05-15T10:57:52.522Z",
      "pdfUrl": "https://drive.google.com/file/d/1E9-YGDmOoH-fkcCD5yl4lK5zrnrPv9bG/view",
      "visible": "private"
    },
    {
      "id": "cmgdmeri60000m7ezhd14vi5j",
      "title": "Event Coordinator",
      "issuer": "C. K. Pithawala College of Engineering and Technology",
      "date": "2025-09-15T00:00:00.000Z",
      "description": "Prompt League Coordinator in INSPIRE '25, a college-level technical festival held on September 15th, 2025, at C. K. Pithawala Campus.",
      "imageUrl": "https://r2.fivemanage.com/image/xKMjdLWUTgsK.png",
      "credentialUrl": null,
      "createdAt": "2025-10-05T11:30:28.155Z",
      "updatedAt": "2025-10-05T11:31:50.774Z",
      "pdfUrl": "https://drive.google.com/file/d/1l0PUFPFsaOXzntw4VirePextJKoxiFyD/view?usp=drive_link",
      "visible": "private"
    }
  ],
  "timelines": [
    {
      "created_at": "2025-12-10T09:59:36.848Z",
      "yearStart": "2021",
      "yearEnd": "2024",
      "ongoing": false,
      "title": "Diploma in Computer Engineering",
      "description": "Completed a Diploma in Computer Engineering with a strong foundation in programming, computer hardware, networking, and software development. Alongside the formal curriculum, independently learned modern web technologies including React and Next.js, building practical skills through personal projects. Developed problem-solving abilities, hands-on technical experience, and a solid base for further growth in the tech field.",
      "type": "Education",
      "id": "17865539-8378-43c1-8102-ba1d5a17bad5"
    }
  ],
  "confirmations": []
} as const;

export async function seedFromGenerated(prismaClient?: PrismaClient) {
  const prisma = prismaClient ?? new PrismaClient();

  // Clear in dependency order
  await prisma.projectCategory.deleteMany();
  await prisma.projectTechnology.deleteMany();
  await prisma.account.deleteMany();
  await prisma.session.deleteMany();
  await prisma.verificationToken.deleteMany();
  await prisma.projects.deleteMany();
  await prisma.technology.deleteMany();
  await prisma.category.deleteMany();
  await prisma.certification.deleteMany();
  await prisma.timeline.deleteMany();
  await prisma.confirmation.deleteMany();
  await prisma.user.deleteMany();

  // Insert base tables
  if (seedData.users.length) {
    await prisma.user.createMany({ data: seedData.users, skipDuplicates: true });
  }
  if (seedData.accounts.length) {
    await prisma.account.createMany({
      data: seedData.accounts,
      skipDuplicates: true,
    });
  }
  if (seedData.sessions.length) {
    await prisma.session.createMany({
      data: seedData.sessions,
      skipDuplicates: true,
    });
  }
  if (seedData.verificationTokens.length) {
    await prisma.verificationToken.createMany({
      data: seedData.verificationTokens,
      skipDuplicates: true,
    });
  }
  if (seedData.technologies.length) {
    await prisma.technology.createMany({
      data: seedData.technologies,
      skipDuplicates: true,
    });
  }
  if (seedData.categories.length) {
    await prisma.category.createMany({
      data: seedData.categories,
      skipDuplicates: true,
    });
  }
  if (seedData.projects.length) {
    await prisma.projects.createMany({
      data: seedData.projects,
      skipDuplicates: true,
    });
  }
  if (seedData.projectTechnologies.length) {
    await prisma.projectTechnology.createMany({
      data: seedData.projectTechnologies,
      skipDuplicates: true,
    });
  }
  if (seedData.projectCategories.length) {
    await prisma.projectCategory.createMany({
      data: seedData.projectCategories,
      skipDuplicates: true,
    });
  }
  if (seedData.certifications.length) {
    await prisma.certification.createMany({
      data: seedData.certifications,
      skipDuplicates: true,
    });
  }
  if (seedData.timelines.length) {
    await prisma.timeline.createMany({
      data: seedData.timelines,
      skipDuplicates: true,
    });
  }
  if (seedData.confirmations.length) {
    await prisma.confirmation.createMany({
      data: seedData.confirmations,
      skipDuplicates: true,
    });
  }

  if (!prismaClient) {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  seedFromGenerated().catch((err) => {
    console.error("❌ Failed to seed from generated data", err);
    process.exit(1);
  });
}
