import Script from 'next/script';
import './globals.css';
import Header from './components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='night' className='h-screen'>
      <body className='w-full h-full max-h-screen'>
        <Header />
        {children}
      </body>
    </html>
  );
}
