import { PrismaClient, Prisma } from "@prisma/client";
import path from "path";
import { writeFile } from "fs/promises";

const prisma = new PrismaClient();

/**
 * Serialize DB data to JSON-safe values.
 * - Dates -> ISO strings
 * - Decimal -> string
 */
function serializeForJson(value: unknown) {
  return JSON.stringify(
    value,
    (_key, val) => {
      if (val instanceof Date) return val.toISOString();
      // Prisma Decimal objects stringify to the numeric string representation
      if (
        val &&
        typeof val === "object" &&
        "toString" in val &&
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore - duck typing for Prisma Decimal
        typeof val.toString === "function" &&
        // Prisma Decimal constructor name can vary, so rely on toString presence
        val.constructor?.name?.toLowerCase().includes("decimal")
      ) {
        return (val as Prisma.Decimal).toString();
      }
      return val;
    },
    2
  );
}

async function safeFindMany<T>(query: () => Promise<T[]>, label: string) {
  try {
    return await query();
  } catch (error) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      (error as { code?: string }).code === "P2021"
    ) {
      // Table is missing in the current DB; return empty so dump still works.
      console.warn(`⚠️  Skipping missing table for ${label} (P2021).`);
      return [];
    }
    throw error;
  }
}

async function fetchAllTables() {
  const [
    users,
    accounts,
    sessions,
    verificationTokens,
    technologies,
    categories,
    projects,
    projectTechnologies,
    projectCategories,
    certifications,
    timelines,
    confirmations,
  ] = await Promise.all([
    safeFindMany(() => prisma.user.findMany(), "user"),
    safeFindMany(() => prisma.account.findMany(), "account"),
    safeFindMany(() => prisma.session.findMany(), "session"),
    safeFindMany(
      () => prisma.verificationToken.findMany(),
      "verificationToken"
    ),
    safeFindMany(() => prisma.technology.findMany(), "technology"),
    safeFindMany(() => prisma.category.findMany(), "category"),
    safeFindMany(() => prisma.projects.findMany(), "projects"),
    safeFindMany(
      () => prisma.projectTechnology.findMany(),
      "projectTechnology"
    ),
    safeFindMany(() => prisma.projectCategory.findMany(), "projectCategory"),
    safeFindMany(() => prisma.certification.findMany(), "certification"),
    safeFindMany(() => prisma.timeline.findMany(), "timeline"),
    safeFindMany(() => prisma.confirmation.findMany(), "confirmation"),
  ]);

  return {
    users,
    accounts,
    sessions,
    verificationTokens,
    technologies,
    categories,
    projects,
    projectTechnologies,
    projectCategories,
    certifications,
    timelines,
    confirmations,
  };
}

function buildSeedFileContent(serializedData: string) {
  return `// Auto-generated by scripts/export-seed.ts
// This file captures the current database state for reseeding.
// Do not edit manually. Regenerate via: bun run seed:dump

import { PrismaClient } from "@prisma/client";

const seedData = ${serializedData} as const;

export async function seedFromGenerated(prismaClient?: PrismaClient) {
  const prisma = prismaClient ?? new PrismaClient();

  // Clear in dependency order
  await prisma.projectCategory.deleteMany();
  await prisma.projectTechnology.deleteMany();
  await prisma.account.deleteMany();
  await prisma.session.deleteMany();
  await prisma.verificationToken.deleteMany();
  await prisma.projects.deleteMany();
  await prisma.technology.deleteMany();
  await prisma.category.deleteMany();
  await prisma.certification.deleteMany();
  await prisma.timeline.deleteMany();
  await prisma.confirmation.deleteMany();
  await prisma.user.deleteMany();

  // Insert base tables
  if (seedData.users.length) {
    await prisma.user.createMany({ data: seedData.users, skipDuplicates: true });
  }
  if (seedData.accounts.length) {
    await prisma.account.createMany({
      data: seedData.accounts,
      skipDuplicates: true,
    });
  }
  if (seedData.sessions.length) {
    await prisma.session.createMany({
      data: seedData.sessions,
      skipDuplicates: true,
    });
  }
  if (seedData.verificationTokens.length) {
    await prisma.verificationToken.createMany({
      data: seedData.verificationTokens,
      skipDuplicates: true,
    });
  }
  if (seedData.technologies.length) {
    await prisma.technology.createMany({
      data: seedData.technologies,
      skipDuplicates: true,
    });
  }
  if (seedData.categories.length) {
    await prisma.category.createMany({
      data: seedData.categories,
      skipDuplicates: true,
    });
  }
  if (seedData.projects.length) {
    await prisma.projects.createMany({
      data: seedData.projects,
      skipDuplicates: true,
    });
  }
  if (seedData.projectTechnologies.length) {
    await prisma.projectTechnology.createMany({
      data: seedData.projectTechnologies,
      skipDuplicates: true,
    });
  }
  if (seedData.projectCategories.length) {
    await prisma.projectCategory.createMany({
      data: seedData.projectCategories,
      skipDuplicates: true,
    });
  }
  if (seedData.certifications.length) {
    await prisma.certification.createMany({
      data: seedData.certifications,
      skipDuplicates: true,
    });
  }
  if (seedData.timelines.length) {
    await prisma.timeline.createMany({
      data: seedData.timelines,
      skipDuplicates: true,
    });
  }
  if (seedData.confirmations.length) {
    await prisma.confirmation.createMany({
      data: seedData.confirmations,
      skipDuplicates: true,
    });
  }

  if (!prismaClient) {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  seedFromGenerated().catch((err) => {
    console.error("❌ Failed to seed from generated data", err);
    process.exit(1);
  });
}
`;
}

async function main() {
  const data = await fetchAllTables();
  const serialized = serializeForJson(data);
  const outputPath = path.join(process.cwd(), "prisma", "seed.generated.ts");

  await writeFile(outputPath, buildSeedFileContent(serialized));
  console.log(`📄 Wrote seed snapshot to ${outputPath}`);
}

main()
  .catch((err) => {
    console.error("❌ Failed to export seed data", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
