name: Check Database

on:
  schedule:
    - cron: "0 0 * * *" # Run at 00:00 UTC every Monday
  workflow_dispatch: # Allows manual triggering

jobs:
  update-projects:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger API endpoint
        run: |
          response=$(curl -X GET https://bhaveshp.dev/api/v1/projects)
          echo "API Response: $response"
